/**:
  ros__parameters:
    input_odom_topic: "/Odometry"
    output_odom_topic: "/odom"
    input_parent_frame: "camera_init"
    input_child_frame: "body"
    output_parent_frame: "odom"
    output_child_frame: "base_link"
    publish_tf: true

    debug:
      enable: true
      log_period_sec: 1.0

    base_to_livox:
      translation: [0.1, 0.0, 0.11]
      rpy: [-0.034, 0.56395, 0.0]

    livox_to_body:
      translation: [-0.012255, -0.016787, 0.050150]
      rpy: [0.0032322401494167274, -0.017154571846166722, 0.003817108262238392]
